# Generated by Django 3.0.3 on 2020-09-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField()),
                ('bookingnumber', models.CharField(max_length=100)),
                ('userid', models.IntegerField()),
                ('idtype', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('checkindate', models.DateField()),
                ('checkoutdate', models.DateField()),
                ('bookingdate', models.DateField()),
                ('remark', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('emailid', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('enquirydate', models.DateField()),
                ('isread', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitytitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=100)),
                ('maxadult', models.IntegerField()),
                ('maxchild', models.IntegerField()),
                ('roomdescription', models.CharField(max_length=500)),
                ('noofbed', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('roomfacility', models.CharField(max_length=200)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Category')),
            ],
        ),
    ]
