# Generated by Django 3.0.3 on 2020-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomfacility',
            field=models.CharField(max_length=500),
        ),
    ]
