# Generated by Django 3.0.3 on 2020-09-24 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_auto_20200921_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
